version: "3.8"

services:
  server:
    image: tryvols/nestjs-api-prod
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
      - SERVER_PORT=3000
      - SERVER_DEBUG_PORT=9229
      - POSTGRES_HOST=db # container name
      - POSTGRES_USER=mentorify_admin
      - POSTGRES_PASSWORD="&1yRICx!^IQ!#M@@k*yjcPXr"
      - POSTGRES_DB=mentorify_db
      - POSTGRES_PORT=5432
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=mentorify_admin
      - POSTGRES_PASSWORD="&1yRICx!^IQ!#M@@k*yjcPXr"
      - POSTGRES_DB=mentorify_db
    ports:
      - 5432:5432
  client:
    image: tryvols/react-client-prod
    working_dir: /usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - db
      - server

# volumes:
#   pgdata:
#     driver: local
