version: "3.8"

services:
  server:
    container_name: nestjs_api__dev
    image: nestjs-api-dev:1.0.0
    init: true
    build:
      context: ./server/gateway
      target: development
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - ./server/gateway:/usr/src/app
      - exclude_node_modules_api_dev:/usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${SERVER_DEBUG_PORT}:9229
    tty: true
    command: bash -c "rm -rf /usr/src/app/node_modules/* && npm run start:debug"
    networks:
      - api-network
    restart: unless-stopped
    depends_on:
      - db
  token_service:
    container_name: nestjs_token__dev
    image: nestjs-token-dev:1.0.0
    init: true
    build:
      context: ./server/token
      target: development
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - ./server/token:/usr/src/app
      - exclude_node_modules_token_dev:/usr/src/app/node_modules
    ports:
      - ${TOKEN_DEBUG_PORT}:9229
    tty: true
    command: bash -c "rm -rf /usr/src/app/node_modules/* && npm run start:dev"
    networks:
      - api-network
    restart: unless-stopped
    depends_on:
      - db
  db:
    container_name: postgres__dev
    image: postgres:14-alpine
    networks:
      - api-network
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

volumes:
  exclude_node_modules_api_dev:
  exclude_node_modules_token_dev:
  pgdata:
