version: "3.8"

services:
  server:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    init: true
    build:
      context: ./server
      target: development
      dockerfile: Dockerfile
    user: "node"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - ./server:/usr/src/app
      - exclude_node_modules_api_dev:/usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${SERVER_DEBUG_PORT}:9229
    tty: true
    command: bash -c "rm -rf /usr/src/app/node_modules/* && npm run start:debug"
    networks:
      - api-network
    restart: unless-stopped
    depends_on:
      - db
  db:
    container_name: postgres_dev
    image: postgres:14-alpine
    networks:
      - api-network
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - api-network

networks:
  api-network:

volumes:
  exclude_node_modules_api_dev:
  pgdata:
